import "@/app/globals.css";
import AppHeader from "@/components/AppHeader";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
  icons: {
    icon: '/layout.ico'
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AppHeader />
        <main className="max-w-5xl mx-auto px-6 py-5">{children}</main>
      </body>
    </html>
  );
}
